// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	blog "echo-blog/bussiness/blog"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: blogDomain
func (_m *Usecase) Create(blogDomain *blog.Domain) blog.Domain {
	ret := _m.Called(blogDomain)

	var r0 blog.Domain
	if rf, ok := ret.Get(0).(func(*blog.Domain) blog.Domain); ok {
		r0 = rf(blogDomain)
	} else {
		r0 = ret.Get(0).(blog.Domain)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Usecase) Delete(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAll provides a mock function with given fields: title
func (_m *Usecase) GetAll(title string) []blog.Domain {
	ret := _m.Called(title)

	var r0 []blog.Domain
	if rf, ok := ret.Get(0).(func(string) []blog.Domain); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]blog.Domain)
		}
	}

	return r0
}

// GetByCategoryID provides a mock function with given fields: id
func (_m *Usecase) GetByCategoryID(id string) []blog.Domain {
	ret := _m.Called(id)

	var r0 []blog.Domain
	if rf, ok := ret.Get(0).(func(string) []blog.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]blog.Domain)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Usecase) GetByID(id string) blog.Domain {
	ret := _m.Called(id)

	var r0 blog.Domain
	if rf, ok := ret.Get(0).(func(string) blog.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(blog.Domain)
	}

	return r0
}

// Update provides a mock function with given fields: id, blogDomain
func (_m *Usecase) Update(id string, blogDomain *blog.Domain) blog.Domain {
	ret := _m.Called(id, blogDomain)

	var r0 blog.Domain
	if rf, ok := ret.Get(0).(func(string, *blog.Domain) blog.Domain); ok {
		r0 = rf(id, blogDomain)
	} else {
		r0 = ret.Get(0).(blog.Domain)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
